language: python
group: travis_latest
dist: xenial

services: xvfb

git:
  depth: 3
  quiet: true

python:
- 3.6

addons:
  apt:
    packages:
    - octave
    - octave-signal

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script: 
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls

install: pip install -e .[tests]

script: pytest -rsv


